In [53]:
print("hello")

hello

In [54]:
import pandas as pd

In [55]:
data = pd.read_csv("Advertising.csv",index_col=0)

In [56]:
data

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [57]:
data.notnull().sum()

TV           200
Radio        200
Newspaper    200
Sales        200
dtype: int64

In [58]:
data

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [59]:
x=data[['TV','Radio','Newspaper']]
y=data[['Sales']]

In [60]:
y

     Sales
1     22.1
2     10.4
3      9.3
4     18.5
5     12.9
..     ...
196    7.6
197    9.7
198   12.8
199   25.5
200   13.4

[200 rows x 1 columns]

In [61]:
                                                                                           # y = b0 + b1x1 + b2x2 + b2x3
! pip install scikit-learn

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

Requirement already satisfied: scikit-learn in c:\users\ritesh\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\ritesh\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in c:\users\ritesh\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ritesh\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ritesh\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)

In [62]:
print(x_train.shape,"Training data size for x")
print(x_test.shape,"Training data size for x")
print(y_train.shape,"Training data size for y")
print(x_test.shape,"Training data size for x")

(160, 3) Training data size for x
(40, 3) Training data size for x
(160, 1) Training data size for y
(40, 3) Training data size for x

In [63]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model= lm.fit(x_train,y_train)

In [64]:
model.coef_

array([[ 0.04563125,  0.19050531, -0.00401356]])

In [65]:
model.intercept_

array([3.00710528])

In [66]:
# y = b0 + b1x1 + b2x2 + b2x3
b0=2.92588052
b1=0.04692506
b2=0.18475563
b3=-0.00357987
y= b0+b1*17.2+b2*45.9+b3*69.3

In [67]:
y

11.965189978

In [68]:
y= b0+b1*180.8+b2*10.8+b3*58.4

In [69]:
y

13.196227764000001

In [70]:
y_pred = model.predict(x_test)

In [71]:
y_pred

array([[18.93566735],
       [ 4.44620593],
       [20.46464632],
       [21.78576147],
       [12.34354275],
       [10.90021123],
       [12.57592618],
       [19.2377701 ],
       [12.37069525],
       [13.87807955],
       [19.33499215],
       [21.15397433],
       [11.98045394],
       [15.59206499],
       [16.36887314],
       [20.76237203],
       [20.80544691],
       [18.03564299],
       [ 9.93327056],
       [18.28634086],
       [13.75063564],
       [15.35663645],
       [14.30476391],
       [18.20419007],
       [ 5.74349751],
       [ 8.527251  ],
       [18.69081636],
       [14.46288608],
       [ 6.58633628],
       [17.44870958],
       [23.26158445],
       [18.60517185],
       [12.11820799],
       [14.1307288 ],
       [ 9.13016161],
       [17.76642464],
       [ 7.92374868],
       [11.66344858],
       [10.61496025],
       [23.04258185]])

In [72]:
new_df = pd.DataFrame()
new_df = x_test
new_df['Actual_Test']= y_test
new_df['predicted_test']= y_pred
new_df

        TV  Radio  Newspaper  Actual_Test  predicted_test
34   265.6   20.0        0.3         17.4       18.935667
193   17.2    4.1       31.6          5.9        4.446206
40   228.0   37.7       32.0         21.5       20.464646
48   239.9   41.5       18.5         23.2       21.785761
2     44.5   39.3       45.1         10.4       12.343543
167   17.9   37.6       21.6          8.0       10.900211
51   199.8    3.1       34.6         11.4       12.575926
134  219.8   33.5       45.1         19.6       19.237770
149   38.0   40.3       11.9         10.9       12.370695
78   120.5   28.5       14.2         14.2       13.878080
125  229.5   32.3       74.2         19.7       19.334992
70   216.8   43.9       27.2         22.3       21.153974
117  139.2   14.3       25.6         12.2       11.980454
26   262.9    3.5       19.5         12.0       15.592065
41   202.5   22.3       31.6         16.6       16.368873
138  273.7   28.9       59.7         20.8       20.762372
85   213.5   43.0       33.8         21.7       20.805447
21   218.4   27.7       53.4         18.0       18.035643
152  121.0    8.4       48.7         11.6        9.933271
142  193.7   35.4       75.6         19.2       18.286341
175  222.4    3.4       13.1         11.5       13.750636
98   184.9   21.0       22.0         15.5       15.356636
172  164.5   20.9       47.4         14.5       14.304764
60   210.7   29.5        9.3         18.4       18.204190
61    53.5    2.0       21.4          8.1        5.743498
57     7.3   28.1       41.4          5.5        8.527251
189  286.0   13.9        3.7         15.9       18.690816
84    68.4   44.5       35.6         13.6       14.462886
118   76.4    0.8       14.8          9.4        6.586336
164  163.5   36.8        7.4         18.0       17.448710
148  243.2   49.0       44.3         25.4       23.261584
194  166.8   42.0        3.6         19.6       18.605172
178  170.2    7.8       35.2         11.7       12.118208
136   48.3   47.0        8.5         11.6       14.130729
126   87.2   11.8       25.9         10.6        9.130162
71   199.1   30.6       38.7         18.3       17.766425
66    69.0    9.3        0.9          9.3        7.923749
87    76.3   27.5       16.0         12.0       11.663449
181  156.6    2.6        8.3         10.5       10.614960
102  296.4   36.3      100.9         23.8       23.042582

In [73]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np

r2 = r2_score(y_test,y_pred)
print('R-squared:',r2)

rmse=np.sqrt(mean_squared_error(y_test,y_pred))
print('RMSE',rmse)

R-squared: 0.9090614098063686
RMSE 1.5507639227831636

In [74]:
data2 = pd.read_csv('Cars.csv',index_col=0)

In [75]:
data2

           MPG  VOL          SP         WT
HP
49   53.700681   89  104.185353  28.762059
55   50.013401   92  105.461264  30.466833
55   50.013401   92  105.461264  30.193597
70   45.696322   92  113.461264  30.632114
53   50.504232   92  104.461264  29.889149
..         ...  ...         ...        ...
322  36.900000   50  169.598513  16.132947
238  19.197888  115  150.576579  37.923113
263  34.000000   50  151.598513  15.769625
295  19.833733  119  167.944460  39.423099
236  12.101263  107  139.840817  34.948615

[81 rows x 4 columns]

In [76]:
data2.isnull().sum()

MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [77]:
data2 = pd.read_csv('Toyota.csv',index_col=0)

In [78]:
data2

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [79]:
data2.isnull().sum()

Price          0
Age          100
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [80]:
data2['Age'].mean

<bound method Series.mean of 0       23.0
1       23.0
2       24.0
3       26.0
4       30.0
        ...
1431     NaN
1432    72.0
1433     NaN
1434    70.0
1435    76.0
Name: Age, Length: 1436, dtype: float64>

In [81]:
mean_age=data2['Age'].mean

In [82]:
data2['Age'].fillna(mean_age,inplace=True)

C:\Users\Ritesh\AppData\Local\Temp\ipykernel_31724\3641176485.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<bound method Series.mean of 0       23.0
1       23.0
2       24.0
3       26.0
4       30.0
        ...
1431     NaN
1432    72.0
1433     NaN
1434    70.0
1435    76.0
Name: Age, Length: 1436, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data2['Age'].fillna(mean_age,inplace=True)

In [83]:
data2.isnull().sum()

Price          0
Age            0
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [84]:
data2["FuelType"].median

<bound method Series.median of 0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...
1431    Petrol
1432    Petrol
1433    Petrol
1434       NaN
1435    Petrol
Name: FuelType, Length: 1436, dtype: object>

In [85]:
median_fuel=data2["FuelType"].median

In [86]:
data2["FuelType"].fillna(median_fuel,inplace=True)

In [87]:
data2.isnull().sum()

Price          0
Age            0
KM             0
FuelType       0
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [88]:
mean_color=data2["MetColor"].mean

In [89]:
data2['MetColor'].fillna(mean_color,inplace=True)

C:\Users\Ritesh\AppData\Local\Temp\ipykernel_31724\3666732580.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<bound method Series.mean of 0       1.0
1       1.0
2       NaN
3       0.0
4       0.0
       ...
1431    1.0
1432    0.0
1433    0.0
1434    1.0
1435    0.0
Name: MetColor, Length: 1436, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data2['MetColor'].fillna(mean_color,inplace=True)

In [90]:
data2.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64

In [91]:
data2

RecursionError: maximum recursion depth exceeded

RecursionError: maximum recursion depth exceeded

In [92]:
data2.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64